services:
  node:
    image: blindtest
    env_file: /data/blindtest/env
    deploy:
      labels:
        - 'traefik.http.routers.blindtest.rule=Host(`blindtest.cube45.fr`)'
        - 'traefik.http.routers.blindtest.tls.certResolver=default'
        - 'traefik.http.services.blindtest.loadbalancer.server.port=80'
        - 'traefik.enable=true'
        - 'traefik.http.routers.blindtest_http.rule=Host(`blindtest.cube45.fr`)'
        - 'traefik.http.middlewares.https_redirect.redirectscheme.scheme=https'
        - 'traefik.http.middlewares.https_redirect.redirectscheme.permanent=true'
        - 'traefik.http.routers.blindtest_http.middlewares=https_redirect'
networks:
  default:
    external: true
    name: proxy_internal
